### ISSUE TITLE
Device of Unknown type: thermostat

### ISSUE THREAD

**Issue by johnathan-arsenault** [jdeath/Hubspace-Homeassistant#143]
Hello, 

I recently purchased the Commercial Electric Thermostat which is on the platform. I was wondering if there was anything I could do to help get this controller added to the supported list?

**Comment by Expl0dingBanana** [comment]
Hello @johnathan-arsenault ! We would need a data dump to get everything configured. Instructions can be found @ https://github.com/jdeath/Hubspace-Homeassistant?tab=readme-ov-file#troubleshooting

**Comment by Expl0dingBanana** [comment]
Hey @johnathan-arsenault ! Following up to see if you were able to generate the data dump so we could add the thermostat!

**Comment by johnathan-arsenault** [comment]
I have not had a chance yet to do this, I will try to get that done tonight or tomorrow.

Thanks for following up!

**Comment by johnathan-arsenault** [comment]
[_dump_hs_devices.json](https://github.com/user-attachments/files/19641939/_dump_hs_devices.json)

Here is the file. thanks again!

**Comment by Expl0dingBanana** [comment]
Got it, thanks! This may take a little bit to get something going as thermostats / climate have a buttload of stuff in them 😅

**Comment by Expl0dingBanana** [comment]
I have reviewed the data dump and think the following is what we should track. Anything in the app you can do thats nots listed / identified here? I am skipping the preset modes as their names are just preset1-6 and id rather not display that in HA.


```
Climate:
	States:
		current_temperature: {"functionClass": "temperature", "functionInstance": "current-temp"}
		fan_mode: {"functionClass": "current-fan-state", "functionInstance": null}
		hvac_action (what you are actively doing) - {"functionClass": "current-system-state"} 
		hvac_mode (what you should be doing to achieve target) - {"functionClass": "mode"}
		max_temp - {"functionClass": "temperature", "functionInstance": "safety-mode-max-temp"}
		min_temp - {"functionClass": "temperature", "functionInstance": "safety-mode-min-temp"}
		target_temperature - Based on hvac_mode:
			- {"functionClass": "temperature", "auto-heating-target"}
			- {"functionClass": "temperature", "auto-cooling-target"}
			- {"functionClass": "temperature", "heating-target"}
			- {"functionClass": "temperature", "cooling-target"}
		temperature_unit - TBD - Everything is in C within the dump but F is selected, so its purely UI
			

	Functions:

		fan_modes - {"functionClass": "fan-mode"}
		hvac_modes - {"functionClass": "mode"}
		target_temperature_high - max({"functionClass": "temperature", "functionInstance": "auto-cooling-target"})
		target_temperature_low - min({"functionClass": "temperature", "functionInstance": "auto-cooling-target"})
		target_temperature_step - 0.5


Binary Sensor:

	State:
		- {"functionClass": "filter-replacement", "functionInstance": null}
		- {"functionClass": "min-temp-exceeded", "functionInstance": null}
		- {"functionClass": "max-temp-exceeded", "functionInstance": null}


Device Attributes:
	State:
		- {"functionClass": "safety-cool-mode", "functionInstance": null}
		- {"functionClass": "safety-heat-mode", "functionInstance": null}
		- {"functionClass": "system-type", "functionInstance": null}
		- {"functionClass": "power-type", "functionInstance": null}
		- {"functionClass": "fan-runtime-in-intermittent-mode", "functionInstance": null}
```

**Comment by johnathan-arsenault** [comment]
that all looks good. having this in HA should allow me to see how fast / slow the temperature changes over time, and make for some pretty cool graphs i think on heat loss during the winter months. maybe add current-system-state so we can see if heat or cool is being called for, but other than that everything else you suggest is great.

**Comment by Expl0dingBanana** [comment]
Sorry life has been busy and will continue to be busy. I am hoping to get to this next week and get thermostats added.

**Comment by johnathan-arsenault** [comment]
no worries, I completely understand!

**Comment by Expl0dingBanana** [comment]
I think it may be close. Just need to do some additional validation!

<img width="407" alt="Image" src="https://github.com/user-attachments/assets/80c89ba0-a78c-4e8b-8bc7-38d7dd1de264" />

<img width="749" alt="Image" src="https://github.com/user-attachments/assets/5f5aaff9-f9be-4ef1-9d5d-9b3776d69531" />

**Comment by Expl0dingBanana** [comment]
Climate properties are now fixed (lack of documentation made it not work)

<img width="242" alt="Image" src="https://github.com/user-attachments/assets/6d971d45-b8f1-4b73-b447-dfef949a4748" />

<img width="427" alt="Image" src="https://github.com/user-attachments/assets/089ff396-dfd1-4ea9-ba87-d373e0ce0106" />

**Comment by johnathan-arsenault** [comment]
Awesome!

**Comment by Expl0dingBanana** [comment]
I am unsure on how the thermostat changes states from fan only -> heat / cool. I would assume it sets fan=on and mode=fan but not positive. Can you grab me the following dumps?

 * Set the system to fan only
 * Generate a debug dump
 * Set the system to heat or cool
 * Generate a debug dump


I think thats my final hurdle for this implementation.

**Comment by johnathan-arsenault** [comment]
here are a few dumps:
fan mode ON
fan mode intermittent 10 minutes every hour
heating mode fan ON no call for heat
heating mode fan AUTO
heating mode fan AUTO Heating

[debug_dump_fan_intermittent_10_min_every_hour.json](https://github.com/user-attachments/files/20068580/debug_dump_fan_intermittent_10_min_every_hour.json)
[debug_dump_fan_mode_on.json](https://github.com/user-attachments/files/20068581/debug_dump_fan_mode_on.json)
[debug_dump_heat_mode_fan_auto.json](https://github.com/user-attachments/files/20068579/debug_dump_heat_mode_fan_auto.json)
[debug_dump_heat_mode_fan_auto_heating.json](https://github.com/user-attachments/files/20068582/debug_dump_heat_mode_fan_auto_heating.json)
[debug_dump_heat_mode_fan_on_no_call_heat.json](https://github.com/user-attachments/files/20068583/debug_dump_heat_mode_fan_on_no_call_heat.json)

**Comment by Expl0dingBanana** [comment]
Thanks for the dumps @johnathan-arsenault ! I will take a look at this tonight

**Comment by Expl0dingBanana** [comment]
I have a dev release out for climate control. Please let me know if you encounter any issues

 * Goto HACS within HA
 * Click `Hubspace-HomeAssistant`
 * Click the triple dots on the top-left
 * Click `Update Information`
 *  Click the triple dots on the top-left
 * Click `Redownload`
 * Click `Show beta versions`
 * Select `dev-add-climate`
 * Click `DOWNLOAD`
 * Restart HA

**Comment by Expl0dingBanana** [comment]
@johnathan-arsenault Were you able to check to see if the thermostat was now controllable in HA?

**Comment by johnathan-arsenault** [comment]
I seem to be getting the following traceback: `Logger: homeassistant.config_entries
Source: config_entries.py:753
First occurred: 8:26:54 PM (2 occurrences)
Last logged: 8:28:51 PM

Error setting up entry johnathan.arsenault@gmail.com for hubspace
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 753, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hubspace/__init__.py", line 28, in async_setup_entry
    if not await bridge.async_initialize_bridge():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hubspace/bridge.py", line 97, in async_initialize_bridge
    await self.hass.config_entries.async_forward_entry_setups(
        self.config_entry, PLATFORMS
    )
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2560, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1184, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1184, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1184, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  [Previous line repeated 6 more times]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1172, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1097, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1271, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1303, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/hubspace/binary_sensor.py", line 2, in <module>
    from aioafero.v1.models import AferoBinarySensor
ImportError: cannot import name 'AferoBinarySensor' from 'aioafero.v1.models' (/usr/local/lib/python3.13/site-packages/aioafero/v1/models/__init__.py)`

**Comment by Expl0dingBanana** [comment]
Oops 3.0.0 was supposed to be pinned after in the manifest file after rebasing the changes. I'll do that tomorrow morning.

**Comment by Expl0dingBanana** [comment]
I have pushed the update to manifest. Re-pull the dev tag and it should be fixed now!

**Comment by johnathan-arsenault** [comment]
I had to manually update the manifest on my end. I'm not sure if my homeassistant instance was caching it..

one thing I did notice is that setting the temperature is not currently working, and the set point's do not move when I set them from hubspace. here's a dump that might show the discrepancies? 

my thermostat is also set up to be single stage heat only, but I'm seeing the cool and heat/cool options in homeassistant, where I do not see those in hubspace.

[_dump_hs_devices.json](https://github.com/user-attachments/files/20162705/_dump_hs_devices.json)

**Comment by Expl0dingBanana** [comment]
I have pushed the above fix. Please re-pull the dev tag and let me know if it works for you! If the logic is incorrect, it can be fixed at a later time but it at least meets the current needs.

**Comment by johnathan-arsenault** [comment]
The temperature settings seem to still not make it to the hubspace backend. I do see that the fixes to not show cooling if it's heating only removes the cooling button, and all the statuses are coming in correctly. the only thing that still seems to need some ironing out if the temperature settings, as I can set heat mode or fan mode and it works.

**Comment by Expl0dingBanana** [comment]
Can you check your logs and see if there are any failures when adjusting the temperature?

**Comment by johnathan-arsenault** [comment]
the api requests are succeeding, but it looks like those values are what needs to be set on temperature change... 

`Making request [put] to https://api2.afero.net/v1/accounts/74cf5cbf-4b20-48fc-bb0b-5debe93b66d3/metadevices/17e15280-addc-4739-9a7b-144a77ab401a/state with {'json': {'metadeviceId': '17e15280-addc-4739-9a7b-144a77ab401a', 'values': [{'functionClass': 'temperature', 'functionInstance': 'auto-heating-target', 'lastUpdateTime': 1747188830, 'value': 15.555555555555555}, {'functionClass': 'temperature', 'functionInstance': 'auto-cooling-target', 'lastUpdateTime': 1747188830, 'value': 24.444444444444443}]}, 'headers': {'host': 'semantics2.afero.net', 'content-type': 'application/json; charset=utf-8'}}
2025-05-13 22:13:50.668 DEBUG (MainThread) [custom_components.hubspace.bridge.thermostat] Received status update for climate.home_heat_thermostat
2025-05-13 22:13:50.671 INFO (MainThread) [aioafero.v1[johnathan.arsenault@gmail.com]] Making request [put] to https://api2.afero.net/v1/accounts/74cf5cbf-4b20-48fc-bb0b-5debe93b66d3/metadevices/17e15280-addc-4739-9a7b-144a77ab401a/state with {'json': {'metadeviceId': '17e15280-addc-4739-9a7b-144a77ab401a', 'values': [{'functionClass': 'temperature', 'functionInstance': 'auto-heating-target', 'lastUpdateTime': 1747188830, 'value': 15.555555555555555}, {'functionClass': 'temperature', 'functionInstance': 'auto-cooling-target', 'lastUpdateTime': 1747188830, 'value': 24.444444444444443}]}, 'headers': {'host': 'semantics2.afero.net', 'content-type': 'application/json; charset=utf-8'}}`

**Comment by johnathan-arsenault** [comment]
it looks like in the case of my thermostat, you need to set heating-target and / or cooling target instead of the auto-heating-target and / or auto-cooling-target

**Comment by johnathan-arsenault** [comment]
I just reloaded entities and now it's working properly.. weird.

**Comment by Expl0dingBanana** [comment]
Is everything working as expected? If so, I will get it merged into main!

**Comment by johnathan-arsenault** [comment]
Everything looks good to me! Hopefully others will have other configurations that can be validated in the future, as I only have 1stage heat
